---
# Helm Chart to deploy
ocp4_workload_hummingbird_repo: https://github.com/redhat-gpte-devopsautomation/agnosticd_workload_helm_charts.git
# Tag to deploy
ocp4_workload_hummingbird_repo_tag: main
ocp4_workload_hummingbird_repo_path: hummingbird

# How many users to set up
ocp4_workload_hummingbird_num_users: 1

# Namespace base (The user number will be appended to this base)
ocp4_workload_hummingbird_namespace_base: rhel-
# Base for multi user setup
ocp4_workload_hummingbird_user_base: user

# Role to grant users for their namespace
ocp4_workload_hummingbird_role: admin

# Settings for the RHEL VMs
ocp4_workload_hummingbird_vm_name_base: rhel-
ocp4_workload_hummingbird_vm_datasourcename: hummingbird
ocp4_workload_hummingbird_vm_datasourcenamespace: openshift-virtualization-os-images
ocp4_workload_hummingbird_vm_user: rhel
# Set password via config
ocp4_workload_hummingbird_vm_password: ""
ocp4_workload_hummingbird_vm_disksize: 30Gi
ocp4_workload_hummingbird_vm_instancetype: u1.medium

# Credentials for the datavolume source (S3 bucket)
ocp4_workload_hummingbird_datavolume_s3_access_key_id: ""
ocp4_workload_hummingbird_datavolume_s3_secret_access_key: ""

# Settings for the DataVolume
ocp4_workload_hummingbird_datavolume_name: hummingbird
ocp4_workload_hummingbird_datavolume_namespace: openshift-virtualization-os-images
ocp4_workload_hummingbird_datavolume_source: http://url_to_qcow2_image.qcow2
ocp4_workload_hummingbird_datavolume_storageClassName: ocs-external-storagecluster-ceph-rbd-immediate
ocp4_workload_hummingbird_datavolume_disksize: 30Gi

# Settings for the DataSource
ocp4_workload_hummingbird_datasource_name: hummingbird
ocp4_workload_hummingbird_datasource_namespace: openshift-virtualization-os-images
ocp4_workload_hummingbird_datasource_pvc_source_name: hummingbird
ocp4_workload_hummingbird_datasource_pvc_source_namespace: openshift-virtualization-os-images

# Settings for the Builds section
ocp4_workload_hummingbird_builds_namespace_base: hummingbird-builds-
ocp4_workload_hummingbird_builds_quay_url: https://quay-registry.example.com
ocp4_workload_hummingbird_builds_quay_admin: quayadmin
ocp4_workload_hummingbird_builds_quay_admin_password: ""
ocp4_workload_hummingbird_builds_quay_oauth_client_id: ""
ocp4_workload_hummingbird_builds_quay_user_password: ""
