---
# Credentials for the datavolume source (S3 bucket)
ocp4_workload_hummingbird_infra_datavolume_s3_access_key_id: ""
ocp4_workload_hummingbird_infra_datavolume_s3_secret_access_key: ""

# Settings for the DataVolume
ocp4_workload_hummingbird_infra_datavolume_name: hummingbird
ocp4_workload_hummingbird_infra_datavolume_namespace: openshift-virtualization-os-images
ocp4_workload_hummingbird_infra_datavolume_source: http://url_to_qcow2_image.qcow2
ocp4_workload_hummingbird_infra_datavolume_storage_class_name: ocs-external-storagecluster-ceph-rbd-immediate
ocp4_workload_hummingbird_infra_datavolume_disksize: 30Gi

# Settings for the DataSource
ocp4_workload_hummingbird_infra_datasource_name: hummingbird
ocp4_workload_hummingbird_infra_datasource_namespace: openshift-virtualization-os-images
ocp4_workload_hummingbird_infra_datasource_pvc_source_name: hummingbird
ocp4_workload_hummingbird_infra_datasource_pvc_source_namespace: openshift-virtualization-os-images

# Settings for additional components
ocp4_workload_hummingbird_infra_keycloak_repo: https://github.com/rhpds/hummingbird-showroom.git
ocp4_workload_hummingbird_infra_keycloak_repo_ref: main
ocp4_workload_hummingbird_infra_keycloak_repo_path: bootstrap/07-keycloak-rhtas

ocp4_workload_hummingbird_infra_rhtas_repo: https://github.com/rhpds/hummingbird-showroom.git
ocp4_workload_hummingbird_infra_rhtas_repo_ref: main
ocp4_workload_hummingbird_infra_rhtas_repo_path: bootstrap/06-rhtas-operator
