---
galaxy_info:
  role_name: ocp4_workload_tenant_quay
  author: Wolfgang Kulhanek <wkulhane@redhat.com>
  description: |
    Deploys (and configures) the a Quay user on an existing Quay Registry
  min_ansible_version: '2.15'
  platforms: []
  license: GNU General Public License v3.0
  galaxy_tags:
  - ocp4
  - openshift
dependencies: []
