---
- name: Create user namespaces and namespace admin rolebindings
  ansible.builtin.include_tasks: build_namespace.yml
  vars:
    _ocp4_workload_hummingbird_tenant_namespace_prefix: "{{ _ocp4_workload_hummingbird_tenant_ns_base_loop }}"
  loop: "{{ ocp4_workload_hummingbird_tenant_namespace_base_list }}"
  loop_control:
    loop_var: _ocp4_workload_hummingbird_tenant_ns_base_loop

- name: Create ClusterRole for Shipwright ClusterBuildStrategies
  kubernetes.core.k8s:
    state: present
    template: clusterrole_builds.yaml.j2

- name: Create ClusterRoleBindings for builds users
  kubernetes.core.k8s:
    state: present
    template: clusterrolebinding_builds.yaml.j2
  loop: "{{ range(1, 1 + ocp4_workload_hummingbird_tenant_num_users | int) | list }}"
