---
- name: Get Quay credentials from user_info
  ansible.builtin.set_fact:
    _ocp4_workload_hummingbird_tenant_quay_url: "{{ lookup('agnosticd_user_data', 'quay_url') | default('undefined') }}"
    _ocp4_workload_hummingbird_tenant_quay_hostname: "{{ lookup('agnosticd_user_data', 'quay_hostname') | default('undefined') }}"
    _ocp4_workload_hummingbird_tenant_quay_user: "{{ lookup('agnosticd_user_data', 'quay_user') | default('undefined') }}"
    _ocp4_workload_hummingbird_tenant_quay_password: "{{ lookup('agnosticd_user_data', 'quay_password') | default('undefined') }}"

- name: Create resources for the lab
  kubernetes.core.k8s:
    state: present
    template: "{{ item }}"
  loop:
  - vm.yaml.j2
  - service-vm.yaml.j2
  - route-vm.yaml.j2
  - clusterrolebinding-builds.yaml.j2

- name: Save VM user information
  agnosticd.core.agnosticd_user_info:
    data:
      rhel_vm_name: "{{ ocp4_workload_hummingbird_tenant_vm_name }}"
      rhel_vm_user: "{{ ocp4_workload_hummingbird_tenant_vm_user }}"
      rhel_vm_password: "{{ ocp4_workload_hummingbird_tenant_vm_password }}"

- name: Get RHACS Route
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: central
    namespace: stackrox
  register: r_rhacs_route

- name: Get RHACS Secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: central-htpasswd
    namespace: stackrox
  register: r_rhacs_secret

- name: Save RHACS user information
  agnosticd.core.agnosticd_user_info:
    data:
      acs_route: "{{ r_rhacs_route.resources[0].spec.host }}"
      acs_username: "admin"
      acs_password: "{{ r_rhacs_secret.resources[0].data.password | b64decode }}"
